# Configuration Netlify pour monorepo Next.js avec pnpm
[build]
  base = "/"
  # Étapes : activer Corepack, installer au workspace, générer Prisma, builder uniquement @terranovision/web
  command = "corepack enable && corepack prepare pnpm@8.15.0 --activate && pnpm install --frozen-lockfile=false && pnpm --filter @terranovision/database prisma generate && pnpm --filter @terranovision/web build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20.17.1"
  PNPM_VERSION = "8.15.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"

# Plugin Next.js officiel pour Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "apps/web/.netlify/functions"
  node_bundler = "esbuild"

# Redirects Next.js
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Cache des assets Next.js
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache des images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
