# Configuration Netlify simplifiée pour Next.js + pnpm monorepo
[build]
  base = "/"
  command = """
    corepack enable && \
    corepack prepare pnpm@8.15.0 --activate && \
    pnpm install --no-frozen-lockfile && \
    pnpm --filter @terranovision/database generate && \
    pnpm --filter @terranovision/web build
  """
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"
  ENABLE_EXPERIMENTAL_COREPACK = "1"
  NEXT_TELEMETRY_DISABLED = "1"

# Plugin Next.js officiel
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects et headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
