name: Build Android APK (Direct)

on:
  workflow_dispatch:
  push:
    tags:
      - 'apk-v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x apps/web/android/gradlew

      - name: Build APK with Gradle
        working-directory: apps/web/android
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: terranovision-apk-debug
          path: apps/web/android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 30
